version: '2'
services:
  web:
      image: linuxchina/boot-demo-docker
      build:
        context: .
        dockerfile: src/main/docker/Dockerfile
      ports:
       - "8080:8080"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"